### PR TITLE
License

### PR DESCRIPTION
**Pull request by galkinAIP**
Customize license settings via base.py in the app

### CODE REVIEW

**Comment by galkinAIP** [comment]
agy-why checked and did not complain ;)

**Comment by galkinAIP** [comment]
Checked

**Comment by jochenklar** [comment]
Sorry, that won't work. With this change you need to create new migrations in daiquiri whenever you change the settings in daiquiri-app, which destroys the separation between the app and the library/package. You could remove the choices from the model fields allt ogether and make them simple TextFields. Then you need to validate the correct choices from the settings (both for the API and the Django admin.)

**Comment by galkinAIP** [comment]
Thanks for the comment! Will fix it then and look at the TextFields option.

**Pull request merged**
