### PR TITLE
Add form honeypot

### PR DESCRIPTION
**Pull request by triole**

### CODE REVIEW

**Review by agy-why — APPROVED** [review]
looks good to me, no further comment. (is it formatted with black?)

**Comment by kimakan** [comment]
For the test I would expect some kind of a failing case. For example, a case where the honeypot field is not empty. Does it make sense to include such a test?

**Comment by agy-why** [comment]
I agree with @kimakan. It would be nice not only to test that we do not break our forms but also that we correctly use the middleware and verify that providing a filled phone field returns a 404.

**Comment by triole** [comment]
Yes, I agree. We should add honeypot tests which respond with a 400 if the field is not filled correctly or missing. I added these two.

**Review by agy-why — APPROVED** [review]
perfect!

**Pull request merged**
