### PR TITLE
Feature tooltip for queryinterface

### PR DESCRIPTION
**Pull request by kimakan**

### CODE REVIEW

**Comment by agy-why** [comment]
It would be great, but not necessary to have the `unit` in the tooltip message for columns.

**Comment by agy-why** [comment]
Similarly, what about adding the signature (parameters) for functions? maybe not necessary since this is shown after double clicking anyway (double info). @kimakan what do you think?

**Comment by kimakan** [comment]
Regarding the signature for the function in the tooltip, thje implementation is not as straight forward as it was in the case of units. Simple solution would be,  adding the signature to the description of the function in the metadata.

**Comment by agy-why** [comment]
I think it is not necessary, let us keep it like that.

**Pull request merged**
